# Copyright 2018 Stefan Seefeld
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE_1_0.txt or copy at http://boost.org/LICENSE_1_0.txt)

version: 1.0.{build}-{branch}

shallow_clone: true

branches:
  only:
    - master
    - develop
    - /feature\/.*/
    - expr_template
    - framework

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Windows
      TOOLSET: msvc-14.13
      CXXSTD: 17
      VSCLCOMPILER: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\cl.exe

cache:
  - C:\tools\vcpkg\installed\


install:
  # Install OpenCL runtime (driver) for Intel / Xeon package
  # - appveyor DownloadFile "http://registrationcenter-download.intel.com/akdlm/irc_nas/9022/opencl_runtime_16.1.1_x64_setup.msi"
  # - start /wait msiexec /i opencl_runtime_16.1.1_x64_setup.msi /qn  /l*v msiexec2.log
  # FIXME: To be removed https://help.appveyor.com/discussions/problems/13000-cmake_toolchain_filevcpkgcmake-conflicts-with-cmake-native-findboostcmake"
  - ps: 'Write-Host "Installing latest vcpkg.cmake module" -ForegroundColor Magenta'
  # - appveyor DownloadFile https://raw.githubusercontent.com/Microsoft/vcpkg/master/scripts/buildsystems/vcpkg.cmake -FileName "C:\tools\vcpkg\scripts\buildsystems\vcpkg.cmake"
  - set "TRIPLET=x64-windows"
  # - vcpkg --triplet %TRIPLET% install opencl clblas
  - set PATH=C:\tools\vcpkg\installed\%TRIPLET%\bin;%PATH%
  - set VCPKG_I=C:\tools\vcpkg\installed\%TRIPLET%\include
  - set VCPKG_L=C:\tools\vcpkg\installed\%TRIPLET%\lib
  - set BOOST_BRANCH=develop
  - if "%APPVEYOR_REPO_BRANCH%" == "master" set BOOST_BRANCH=master
  - cd ..
  - cd
  # - git clone -b %BOOST_BRANCH% https://github.com/boostorg/boost.git boost-root
  - cd boost-root
  # - git submodule update --init tools/build
  # - git submodule update --init libs/config
  # - git submodule update --init tools/boostdep
  # - xcopy /s /e /q %APPVEYOR_BUILD_FOLDER% libs\numeric\ublas /Y
  # - python tools/boostdep/depinst/depinst.py -I benchmarks numeric/ublas
  # - xcopy %APPVEYOR_BUILD_FOLDER%\opencl.jam %USERPROFILE% /Y
  # - xcopy %APPVEYOR_BUILD_FOLDER%\clblas.jam %USERPROFILE% /Y
  - ps: |
      # Creating %USERPROFILE%/user-config.jam file
      @'
      import os regex toolset ;
      local tool_path = [ os.environ VSCLCOMPILER ] ;
      local toolset = [ regex.split [ os.environ TOOLSET ] "-" ] ;
      local vcpkg_i = [ os.environ VCPKG_I ] ;
      local vcpkg_l = [ os.environ VCPKG_L ] ;
      using $(toolset[1]) : $(toolset[2-]:J="-") : $(tool_path) : ;
      using opencl : : <include>$(vcpkg_i) <search>$(vcpkg_l) ;
      using clblas : : <include>$(vcpkg_i) <search>$(vcpkg_l) ;
      '@ | sc "$env:USERPROFILE/user-config.jam"
  # - cmd /c bootstrap
  - b2 -j3 headers

build: off

test_script:
  #- PATH=%ADDPATH%%PATH%
  - if not "%CXXSTD%" == "" set CXXSTD=cxxstd=%CXXSTD%
  - set ADDRMD=address-model=64
  - b2 -j3 libs/numeric/ublas/test toolset=%TOOLSET% %CXXSTD% %ADDRMD%
  - b2 -j3 libs/numeric/ublas/benchmarks toolset=%TOOLSET% %CXXSTD% %ADDRMD%
  - b2 -j3 libs/numeric/ublas/examples/tensor toolset=%TOOLSET% %CXXSTD% %ADDRMD%
